# Generated by Django 4.1.2 on 2022-12-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default=494, max_length=255),
            preserve_default=False,
        ),
    ]
