# Generated by Django 4.1.2 on 2022-12-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='membership_choice',
        ),
        migrations.AddField(
            model_name='customer',
            name='membership_choice',
            field=models.CharField(choices=[('B', 'Bronze'), ('G', 'Gold'), ('D', 'Diamond')], default='B', max_length=1),
        ),
    ]
