# Generated by Django 4.1.2 on 2022-12-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='collection_of_products',
            new_name='collection_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promotions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.ManyToManyField(to='store.promotion', verbose_name='Promotion for product'),
        ),
    ]
