# Generated by Django 4.1.2 on 2022-12-29 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_promotions_remove_product_slug_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.collection', verbose_name='collection of multiple products'),
        ),
    ]
