# Generated by Django 4.1.2 on 2022-12-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_collection_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cutomer_order',
            new_name='cutomer_id',
        ),
    ]
