# Generated by Django 4.1.2 on 2022-12-30 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_cutomer_order_order_cutomer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cutomer_id',
            new_name='cutomer',
        ),
    ]
