# Generated by Django 4.1.2 on 2022-12-30 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_cutomer_id_order_cutomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cutomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer', verbose_name='order of customer'),
        ),
    ]
